# Generated by Django 5.1.2 on 2024-12-09 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deduction',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='empoyee_id',
            new_name='employee_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='status',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='position',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='position',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='allowance',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_days_per_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='payment_method',
            field=models.CharField(default=33874, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='action_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.DeleteModel(
            name='Overtime',
        ),
        migrations.DeleteModel(
            name='TimeSheet',
        ),
    ]
