# Generated by Django 5.1.2 on 2024-12-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0002_alter_employee_options_remove_employee_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
