# Generated by Django 5.1.2 on 2024-12-11 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
