# Generated by Django 5.1.2 on 2024-12-31 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0003_employee_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
    ]
