# Generated by Django 5.1.2 on 2024-12-02 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyresult',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='okrapp.objective'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
