# Generated by Django 5.1.2 on 2024-11-27 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentshare',
            name='permission',
            field=models.CharField(choices=[('view', 'View Only'), ('edit', 'Edit'), ('full', 'Full Access')], default='view', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shares', to=settings.AUTH_USER_MODEL),
        ),
    ]
