# Generated by Django 5.1.2 on 2024-11-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_document_shared_with_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='document',
            name='version',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
