# Generated by Django 5.1.2 on 2024-12-12 17:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='company')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('hr_admin', 'HR Admin'), ('hr_manager', 'HR Manager'), ('hr_staff', 'HR Staff'), ('accounting_admin', 'Accounting Admin'), ('accountant', 'Accountant'), ('project_admin', 'Project Admin'), ('project_manager', 'Project Manager'), ('project_member', 'Project Member'), ('crm_admin', 'CRM Admin'), ('crm_manager', 'CRM Manager'), ('sales_rep', 'Sales Representative'), ('client', 'Client')], default='client', max_length=20, verbose_name='role')),
                ('primary_module', models.CharField(choices=[('hrm', 'Human Resources'), ('accounting', 'Accounting'), ('project', 'Project Management'), ('crm', 'Customer Relationship'), ('meeting', 'Meeting Management')], max_length=20, null=True, verbose_name='primary module')),
                ('accessible_modules', models.JSONField(default=list, help_text='List of modules this user can access', verbose_name='accessible modules')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='phone number')),
                ('department', models.CharField(blank=True, default='', max_length=100, verbose_name='department')),
                ('position', models.CharField(blank=True, default='', max_length=100, verbose_name='position')),
                ('bio', models.TextField(blank=True, default='', verbose_name='biography')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'ordering': ['user__email'],
            },
        ),
    ]
